import type { RecipeDraft } from '@/lib/recipe-schema';

export const STARTER_RECIPES: { draft: RecipeDraft; sourceUrl: string }[] = [
  {
    sourceUrl: 'https://www.momontimeout.com/easy-chicken-stir-fry-recipe/',
    draft: {
      title: 'Easy Chicken Stir Fry Recipe', creator: 'Trish - Mom On Timeout', category: 'Dinner',
      prepMinutes: 8, cookMinutes: 10, servings: 4,
      ingredients: [
        { position: 0, quantity: '1 lb', unit: null, name: 'boneless, skinless chicken breast', notes: 'cut into 1 inch cubes', aisle: 'Produce' },
        { position: 1, quantity: null, unit: null, name: 'salt', notes: 'to taste', aisle: 'Pantry' },
        { position: 2, quantity: null, unit: null, name: 'pepper', notes: 'to taste', aisle: 'Pantry' },
        { position: 3, quantity: '2 tbsp', unit: 'tbsp', name: 'olive oil', notes: 'divided', aisle: 'Pantry' },
        { position: 4, quantity: '2 cups', unit: 'cups', name: 'broccoli florets', notes: null, aisle: 'Produce' },
        { position: 5, quantity: '1/2', unit: null, name: 'yellow bell pepper', notes: 'cut into 1 inch pieces', aisle: 'Produce' },
        { position: 6, quantity: '1/2', unit: null, name: 'red bell pepper', notes: 'cut into 1 inch pieces', aisle: 'Produce' },
        { position: 7, quantity: '1/2 cup', unit: 'cup', name: 'baby carrots', notes: 'sliced', aisle: 'Produce' },
        { position: 8, quantity: '2 tsp', unit: 'tsp', name: 'ginger', notes: 'minced', aisle: 'Produce' },
        { position: 9, quantity: '2', unit: 'clove', name: 'garlic', notes: 'minced', aisle: 'Produce' },
        { position: 10, quantity: '1 tbsp', unit: 'tbsp', name: 'corn starch', notes: null, aisle: 'Pantry' },
        { position: 11, quantity: '2 tbsp', unit: 'tbsp', name: 'cold water', notes: null, aisle: 'Pantry' },
        { position: 12, quantity: '1/4 cup', unit: 'cup', name: 'low sodium chicken broth', notes: null, aisle: 'Dairy & chilled' },
        { position: 13, quantity: '3 tbsp', unit: 'tbsp', name: 'low sodium soy sauce', notes: null, aisle: 'Pantry' },
        { position: 14, quantity: '1/4 cup', unit: 'cup', name: 'honey', notes: null, aisle: 'Pantry' },
        { position: 15, quantity: '1 tbsp', unit: 'tbsp', name: 'toasted sesame oil', notes: null, aisle: 'Pantry' },
        { position: 16, quantity: '1/2 tsp', unit: 'tsp', name: 'crushed red pepper flakes', notes: 'completely optional', aisle: 'Pantry' },
      ],
      steps: [
        { position: 0, instruction: 'In a medium size bowl, whisk together corn starch and water. Add remaining ingredients (chicken broth, soy sauce, honey, and toasted sesame oil, red pepper flakes) and whisk to combine. Set aside.' },
        { position: 1, instruction: 'Add one tablespoon of olive oil to a large skillet or wok and heat over medium high heat.' },
        { position: 2, instruction: 'Add chicken (in batches if necessary) and season with salt and pepper. Cook for 3 to 5 minutes or until cooked through. Remove from skillet.' },
        { position: 3, instruction: 'Reduce heat to medium and add remaining tablespoon of oil to the skillet.' },
        { position: 4, instruction: 'Add broccoli, bell pepper, and carrots and cook, stirring occasionally, just until crisp tender.' },
        { position: 5, instruction: 'Add ginger and garlic and cook for an additional minute.' },
        { position: 6, instruction: 'Add chicken back into the skillet and stir to combine.' },
        { position: 7, instruction: 'Whisk stir fry sauce and pour over chicken and vegetables and stir gently to combine.' },
        { position: 8, instruction: 'Bring to a boil, stirring occasionally, and let boil for one minute.' },
        { position: 9, instruction: 'Serve with rice and/or chow mein if desired.' },
      ],
    },
  },
  {
    sourceUrl: 'https://breaddad.com/easy-banana-bread-recipe/',
    draft: {
      title: 'Easy Banana Bread Recipe', creator: 'Bread Dad', category: 'Dessert',
      prepMinutes: 10, cookMinutes: 60, servings: 8,
      ingredients: [
        { position: 0, quantity: '3', unit: null, name: 'ripe bananas', notes: 'mashed', aisle: 'Produce' },
        { position: 1, quantity: '1/3 cup', unit: 'cup', name: 'melted butter', notes: null, aisle: 'Dairy & chilled' },
        { position: 2, quantity: '3/4 cup', unit: 'cup', name: 'sugar', notes: null, aisle: 'Pantry' },
        { position: 3, quantity: '1', unit: null, name: 'egg', notes: 'beaten', aisle: 'Dairy & chilled' },
        { position: 4, quantity: '1 tsp', unit: 'tsp', name: 'vanilla extract', notes: null, aisle: 'Pantry' },
        { position: 5, quantity: '1 tsp', unit: 'tsp', name: 'baking soda', notes: null, aisle: 'Pantry' },
        { position: 6, quantity: '1/4 tsp', unit: 'tsp', name: 'salt', notes: null, aisle: 'Pantry' },
        { position: 7, quantity: '1 1/2 cups', unit: 'cups', name: 'all-purpose flour', notes: null, aisle: 'Pantry' },
      ],
      steps: [
        { position: 0, instruction: 'Preheat the oven to 350°F. Butter a 4x8 inch loaf pan.' },
        { position: 1, instruction: 'In a large bowl, mix the melted butter into the mashed bananas.' },
        { position: 2, instruction: 'Mix in the sugar, egg, and vanilla.' },
        { position: 3, instruction: 'Sprinkle the baking soda and salt over the mixture and mix in.' },
        { position: 4, instruction: 'Add the flour and mix until just combined.' },
        { position: 5, instruction: 'Pour the batter into the prepared loaf pan.' },
        { position: 6, instruction: 'Bake for 55 to 65 minutes, until a toothpick inserted in the center comes out clean.' },
        { position: 7, instruction: 'Cool in the pan for a few minutes, then remove to a wire rack to cool completely before slicing.' },
      ],
    },
  },
  {
    sourceUrl: 'https://www.elizabethrider.com/breakfast-burritos/',
    draft: {
      title: 'Breakfast Burritos', creator: 'Elizabeth Rider', category: 'Breakfast',
      prepMinutes: 10, cookMinutes: 15, servings: 4,
      ingredients: [
        { position: 0, quantity: '8', unit: null, name: 'eggs', notes: null, aisle: 'Dairy & chilled' },
        { position: 1, quantity: '1/4 cup', unit: 'cup', name: 'milk', notes: null, aisle: 'Dairy & chilled' },
        { position: 2, quantity: null, unit: null, name: 'salt', notes: 'to taste', aisle: 'Pantry' },
        { position: 3, quantity: null, unit: null, name: 'pepper', notes: 'to taste', aisle: 'Pantry' },
        { position: 4, quantity: '1 tbsp', unit: 'tbsp', name: 'olive oil', notes: null, aisle: 'Pantry' },
        { position: 5, quantity: '1/2', unit: null, name: 'onion', notes: 'diced', aisle: 'Produce' },
        { position: 6, quantity: '1', unit: null, name: 'bell pepper', notes: 'diced', aisle: 'Produce' },
        { position: 7, quantity: '1 cup', unit: 'cup', name: 'black beans', notes: 'drained and rinsed', aisle: 'Pantry' },
        { position: 8, quantity: '1 cup', unit: 'cup', name: 'shredded cheddar cheese', notes: null, aisle: 'Dairy & chilled' },
        { position: 9, quantity: '4', unit: null, name: 'large flour tortillas', notes: null, aisle: 'Pantry' },
        { position: 10, quantity: null, unit: null, name: 'salsa', notes: 'for serving, optional', aisle: 'Pantry' },
      ],
      steps: [
        { position: 0, instruction: 'Whisk eggs, milk, salt, and pepper together in a bowl.' },
        { position: 1, instruction: 'Heat olive oil in a skillet over medium heat and saute the onion and bell pepper until softened, about 5 minutes.' },
        { position: 2, instruction: 'Add the black beans and cook for another minute to warm through.' },
        { position: 3, instruction: 'Push vegetables to the side, pour in the eggs, and scramble until just set.' },
        { position: 4, instruction: 'Remove from heat and stir in the shredded cheese.' },
        { position: 5, instruction: 'Warm the tortillas, then divide the egg mixture among them.' },
        { position: 6, instruction: 'Fold in the sides and roll up each tortilla into a burrito.' },
        { position: 7, instruction: 'Serve immediately with salsa if desired.' },
      ],
    },
  },
  {
    sourceUrl: 'https://www.instagram.com/reel/DayYqvdPSaV/?utm_source=ig_web_button_share_sheet',
    draft: {
      title: 'Cajun butter steak bites over parmesan mashed potatoes', creator: 'nutritionwithnat', category: 'Dinner',
      prepMinutes: null, cookMinutes: null, servings: null,
      ingredients: [
        { position: 0, quantity: '4', unit: 'tbsp', name: 'unsalted butter', notes: 'softened', aisle: 'Dairy & chilled' },
        { position: 1, quantity: '1/2', unit: 'tsp', name: 'seasoned Cajun', notes: null, aisle: 'Pantry' },
        { position: 2, quantity: '1', unit: 'tsp', name: 'parsley', notes: null, aisle: 'Produce' },
        { position: 3, quantity: '2', unit: 'tsp', name: 'garlic', notes: 'minced', aisle: 'Produce' },
        { position: 4, quantity: '1', unit: 'tsp', name: 'lemon juice', notes: null, aisle: 'Produce' },
        { position: 5, quantity: '1/2', unit: 'tsp', name: 'Dijon mustard', notes: null, aisle: 'Pantry' },
        { position: 6, quantity: '2', unit: null, name: 'steaks', notes: 'trim into 1 inch pieces', aisle: 'Pantry' },
        { position: 7, quantity: '1', unit: 'tbsp', name: 'Worcestershire sauce', notes: null, aisle: 'Pantry' },
        { position: 8, quantity: '1', unit: 'tsp', name: 'buttery steakhouse seasoning', notes: null, aisle: 'Pantry' },
        { position: 9, quantity: null, unit: null, name: 'avocado oil', notes: 'for cooking', aisle: 'Pantry' },
        { position: 10, quantity: '2', unit: 'tbsp', name: 'Cajun butter', notes: null, aisle: 'Pantry' },
        { position: 11, quantity: null, unit: null, name: 'asparagus', notes: 'seasoned with lemon juice, garlic powder, salt, pepper, Parmesan cheese', aisle: 'Produce' },
        { position: 12, quantity: null, unit: null, name: 'garlic powder', notes: null, aisle: 'Pantry' },
        { position: 13, quantity: null, unit: null, name: 'salt', notes: null, aisle: 'Pantry' },
        { position: 14, quantity: null, unit: null, name: 'pepper', notes: null, aisle: 'Pantry' },
        { position: 15, quantity: null, unit: null, name: 'Parmesan cheese', notes: 'for asparagus', aisle: 'Dairy & chilled' },
        { position: 16, quantity: '2', unit: null, name: 'gold potatoes', notes: 'large, peeled and diced', aisle: 'Produce' },
        { position: 17, quantity: '1/2', unit: 'cup', name: 'heavy cream', notes: null, aisle: 'Dairy & chilled' },
        { position: 18, quantity: '2', unit: 'tbsp', name: 'sour cream', notes: null, aisle: 'Dairy & chilled' },
        { position: 19, quantity: '1/4', unit: 'cup', name: 'Parmesan cheese', notes: null, aisle: 'Dairy & chilled' },
        { position: 20, quantity: '1/2', unit: 'tbsp', name: 'butter', notes: null, aisle: 'Dairy & chilled' },
      ],
      steps: [
        { position: 0, instruction: 'Mix Cajun butter ingredients (unsalted butter, seasoned Cajun, parsley, minced garlic, lemon juice, Dijon mustard) until combined; optional add red pepper flakes.' },
        { position: 1, instruction: 'Trim steaks into 1-inch pieces and season with Worcestershire sauce and buttery steakhouse seasoning.' },
        { position: 2, instruction: 'Let the seasoned steak bites rest before cooking.' },
        { position: 3, instruction: 'Heat avocado oil in a pan over medium/high heat; add steak bites and cook 1-2 minutes per side.' },
        { position: 4, instruction: 'Reduce heat and stir in 2 tbsp Cajun butter; toss steak bites for an additional minute.' },
        { position: 5, instruction: 'Remove steak bites; add asparagus to the pan and season with lemon juice, garlic powder, salt, pepper, and Parmesan cheese.' },
        { position: 6, instruction: 'Peel and dice 2 large gold potatoes into 1-inch cubes; boil in salted water until tender, then drain and mash.' },
        { position: 7, instruction: 'Stir heavy cream, sour cream, Parmesan cheese, butter, salt, pepper, and garlic powder into the mashed potatoes.' },
        { position: 8, instruction: 'Assemble: place creamy Parmesan mashed potatoes in a bowl, top with Cajun butter steak bites, serve with asparagus, ciabatta, and garnish with parsley.' },
      ],
    },
  },
  {
    sourceUrl: 'https://youtu.be/C-5g4qfKSoY',
    draft: {
      title: 'THICK vegan Mayo Recipe made from CHICKPEAS (aquafaba)!', creator: 'Wil Yeung', category: 'Other',
      prepMinutes: null, cookMinutes: null, servings: null,
      ingredients: [
        { position: 0, quantity: '400', unit: 'ml', name: 'chickpeas', notes: 'roughly 3/4 cups aquafaba', aisle: 'Pantry' },
        { position: 1, quantity: '1', unit: 'tbsp', name: 'lemon juice', notes: null, aisle: 'Pantry' },
        { position: 2, quantity: '1', unit: 'tbsp', name: 'canned chickpeas', notes: null, aisle: 'Pantry' },
        { position: 3, quantity: '1', unit: 'tbsp', name: 'dijon mustard', notes: null, aisle: 'Pantry' },
        { position: 4, quantity: '1 3/4', unit: 'cup', name: 'grapeseed oil or vegetable oil', notes: 'drizzle in a little more for an even thicker mayo', aisle: 'Pantry' },
        { position: 5, quantity: null, unit: null, name: 'pink salt', notes: 'generous pinch', aisle: 'Pantry' },
        { position: 6, quantity: '1', unit: 'part', name: 'gochujang', notes: 'optional, add 1 part to 2 parts mayo', aisle: 'Pantry' },
      ],
      steps: [
        { position: 0, instruction: 'Empty the can of chickpea water (aquafaba) into a small saucepan.' },
        { position: 1, instruction: 'Boil the aquafaba on medium high heat for 5-6 minutes, stirring often.' },
        { position: 2, instruction: 'Add some ice to a large mixing bowl, then place a smaller bowl on top of the ice.' },
        { position: 3, instruction: 'Pour in the chickpea water and stir until cold.' },
        { position: 4, instruction: 'Add the lemon juice and 1 tbsp of chickpeas.' },
        { position: 5, instruction: 'Transfer the mixture to the blender and add the dijon mustard.' },
        { position: 6, instruction: 'Blend on the highest setting to pulverize the chickpeas, then turn it down to medium to medium high.' },
        { position: 7, instruction: 'Slowly pour in the oil; the mayo will start to thicken up (adjust and pulse the speed if needed).' },
        { position: 8, instruction: 'Transfer the mayo to a mixing bowl and add a generous pinch of pink salt. Fold to combine.' },
      ],
    },
  },
];
